version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: order-management-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_management
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: order-management-api
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/order_management
      - NODE_ENV=production
    command: pnpm --filter api start

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: order-management-web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
      - NODE_ENV=production
    command: pnpm --filter web start

volumes:
  postgres-data:
